# X570

# Center Ultrawide
monitorrule=model:34G1R,width:3440,height:1440,refresh:165.0,x:0,y:0
# Right side vertical
monitorrule=serial:TDZAA0023P00,width:2560,height:1440,refresh:74.598999,rr:3,x:3440,y:0

# Noctalia Bar needs per monitor definition
layerrule=noanim:1,noblur:1,layer_name:noctalia-bar-content-DP-1
layerrule=noanim:1,noblur:1,layer_name:noctalia-bar-content-HDMI-A-3

