# This works on my nixos systems
exec-once=noctalia-shell
exec-once=noctalia-path

bind=SUPER,space,spawn,noctalia-wrapper ipc call launcher toggle
bind=SUPER+CTRL,L,spawn,noctalia-wrapper ipc call lockScreen lock
bind=SUPER+CTRL,space,spawn,noctalia-wrapper ipc call bar toggle

